Add Jenkins pipeline for AWS ECR deployment

diff --git a/Jenkins b/Jenkins
--- a/Jenkins
+++ b/Jenkins
@@ -1,1 +1,111 @@
-hi
+pipeline {
+    agent any
+
+    environment {
+        GIT_REPO = 'https://github.com/NarutItachi/Jenkins-Docker-Project.git'
+        AWS_REGION = 'ap-south-1'
+        ECR_REPO_NAME = 'jenkins-docker-project'
+        ECR_PUBLIC_REPO_URI = '467968377806.dkr.ecr.ap-south-1.amazonaws.com/jenkins-docker-project'
+        IMAGE_TAG = '1.0'
+        AWS_ACCOUNT_ID = '467968377806'
+        IMAGE_URI = "docker-image:1.0"
+        EKS_CLUSTER = 'my-eks-cluster'
+    }
+
+    stages {
+        stage('Install AWS CLI') {
+            steps {
+                script {
+                    sh '''
+                        set -e
+                        echo "Installing AWS CLI..."
+                        sudo apt update && sudo apt install -y unzip curl
+
+                        curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
+                        rm -rf aws
+                        unzip -q awscliv2.zip
+                        sudo ./aws/install --update
+                        aws --version
+                    '''
+                }
+            }
+        }
+
+             stage('Configure AWS Credentials') {
+    steps {
+        script {
+            sh '''
+            echo "Setting up AWS credentials for Jenkins..."
+            mkdir -p /var/lib/jenkins/.aws
+            echo "[default]" > /var/lib/jenkins/.aws/credentials
+            echo "aws_access_key_id=AKIAWN26KB25BRBD26NF" >> /var/lib/jenkins/.aws/credentials
+            echo "aws_secret_access_key=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" >> /var/lib/jenkins/.aws/credentials
+            chown -R jenkins:jenkins /var/lib/jenkins/.aws
+            '''
+        }
+    }
+}
+
+
+        stage('Clone Repository') {
+            steps {
+                git url: "https://github.com/NarutItachi/Jenkins-Docker-Project.git", branch: 'main'
+            }
+        }
+
+        stage('Build') {
+            steps {
+                script {
+                    sh '''
+                        echo "Building Java application..."
+                        mvn clean -B -Denforcer.skip=true package
+                    '''
+                }
+            }
+        }
+
+        stage('Login to AWS ECR') {
+            steps {
+                script {
+                    sh '''
+                        echo "Logging into AWS ECR..."
+                        aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws
+                    '''
+                }
+            }
+        }
+
+        stage('Build Docker Image') {
+            steps {
+                script {
+                    sh '''
+                        echo "Building Docker image..."
+                        docker build -t docker-image:1.0 .
+                    '''
+                }
+            }
+        }
+
+        stage('Push Docker Image to ECR') {
+            steps {
+                script {
+                    sh '''
+                        echo "Pushing Docker image to ECR..."
+                        docker push docker-image:1.0
+                    '''
+                }
+            }
+        }
+
+    }
+    
+    post {
+        success {
+            echo "Docker image pushed to ECR successfully and deployed."
+        }
+        failure {
+            echo "Pipeline failed."
+        }
+    }
+}
+
